export const botBites = [
    {
        foodName: 'Nasi Goreng Gila Gondrong Obama',
        locationName: 'Nasi Goreng Obama Menteng',
        locationAddress: 'Jl. Besuki No. 4, Menteng, Jakarta Pusat',
        latitude: '-6.20015',
        longitude: '106.82944',
        placeId: 'place_obama_001',
        review: 'Nasi goreng gila legendaris di Menteng. Isian sosis, bakso, telur, dan bumbu gilanya melimpah banget. Porsinya bikin kenyang dan rasanya gurih manis pedas pas mantap!',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
        category: 'street_food',
    },
    {
        foodName: 'Soto Betawi H. Mamat',
        locationName: 'Soto Betawi H. Mamat BSD',
        locationAddress: 'Jl. Letnan Sutopo, Serpong, Tangerang Selatan',
        latitude: '-6.30211',
        longitude: '106.68532',
        placeId: 'place_mamat_001',
        review: 'Soto Betawi oseng dagingnya juara! Dagingnya ditumis dulu dengan bawang dan cabe rawit, terus disajikan pisah sama kuah santan hangat yang super gurih. Juara dunia pokoknya.',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
        category: 'street_food',
    },
    {
        foodName: 'Es Kopi Susu Tetangga',
        locationName: 'Toko Kopi Tuku Cipete',
        locationAddress: 'Jl. Cipete Raya No. 7, Cilandak, Jakarta Selatan',
        latitude: '-6.27318',
        longitude: '106.80521',
        placeId: 'place_tuku_001',
        review: 'Es Kopi Susu pioneer dengan gula aren. Creamy-nya dapet, kopinya tetep berasa, dan manis gula arennya pas banget. Selalu jadi go-to kopi tiap pagi.',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        category: 'cafe',
    },
    {
        foodName: 'Sourdough Avocado Toast',
        locationName: 'One Fifteenth Coffee Menteng',
        locationAddress: 'Jl. Dr. Kusuma Atmaja No. 85, Menteng, Jakarta Pusat',
        latitude: '-6.19825',
        longitude: '106.82412',
        placeId: 'place_one_fifteenth_001',
        review: 'Avocado toast paling fresh dengan poached egg yang dimasak perfectly runny. Roti sourdough-nya crunchy di luar dan lembut di dalem. Kopi flat white-nya juga juara di sini.',
        rating: 4,
        photoUrl: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=800',
        category: 'cafe',
    },
    {
        foodName: 'Wagyu Ribeye MB9+ Steak',
        locationName: 'Bistecca SCBD',
        locationAddress: '18 Parc Place SCBD, Jl. Jend. Sudirman, Jakarta Selatan',
        latitude: '-6.22387',
        longitude: '106.81155',
        placeId: 'place_bistecca_001',
        review: 'Salah satu steakhouse terbaik di Jakarta. Daging wagyu MB9+ dimasak medium rare sempurna dengan sear crust yang gurih banget. Dagingnya lumer di mulut (melt-in-the-mouth texture). Worth every penny!',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
        category: 'fine_dining',
    },
    {
        foodName: 'Truffle Tagliolini Pasta',
        locationName: 'Osteria Gia Plaza Indonesia',
        locationAddress: 'Plaza Indonesia Lt. G, Menteng, Jakarta Pusat',
        latitude: '-6.19324',
        longitude: '106.82298',
        placeId: 'place_osteria_gia_001',
        review: 'Sajian pasta truffle-nya sangat aromatik. Saus creamy mentega berpadu dengan parutan fresh black truffle di atas pasta tagliolini buatan sendiri. Rasanya rich dan mewah!',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
        category: 'fine_dining',
    },
    {
        foodName: 'Massimo Gelato 3 Flavors',
        locationName: 'Massimo Gelato Jakarta',
        locationAddress: 'Jl. Kemang Selatan No. 10, Pasar Minggu, Jakarta Selatan',
        latitude: '-6.27891',
        longitude: '106.81744',
        placeId: 'place_massimo_001',
        review: 'Gelato khas Bali sekarang ada di Jakarta! Nyobain rasa Pistachio, Dark Chocolate, sama Sea Salt. Teksturnya padat, rasanya intens, manisnya ga lebay. Porsinya super banyak buat harga segitu.',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
        category: 'dessert',
    },
    {
        foodName: 'Original Belgian Croffle',
        locationName: 'Social House Grand Indonesia',
        locationAddress: 'Grand Indonesia East Mall Lt. 1, Jakarta Pusat',
        latitude: '-6.19515',
        longitude: '106.82099',
        placeId: 'place_soho_croffle_001',
        review: 'Croffle-nya wangi butter banget, luarnya terkaramelisasi dengan baik jadi crunchy tapi dalemnya tetep lembut. Ditambah satu scoop vanilla gelato di atasnya, perfect dessert combo!',
        rating: 4,
        photoUrl: 'https://images.unsplash.com/photo-1562376502-6f769499c886?w=800',
        category: 'dessert',
    },
    {
        foodName: 'Souffle Pancake Strawberry',
        locationName: 'Pan & Co Senayan City',
        locationAddress: 'Senayan City Lt. 5, Tanah Abang, Jakarta Pusat',
        latitude: '-6.22722',
        longitude: '106.79744',
        placeId: 'place_panco_001',
        review: 'Pancake jepang yang super jiggly dan fluffy! Pas dimakan lembut banget langsung lumer kayak awan. Saus strawberry-nya seger asem-manis, ga bikin eneg.',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
        category: 'viral',
    },
    {
        foodName: 'Mie Level 8 Pedas Mampus',
        locationName: 'Mie Gacoan Tebet',
        locationAddress: 'Jl. Tebet Raya No. 35, Tebet, Jakarta Selatan',
        latitude: '-6.22998',
        longitude: '106.84888',
        placeId: 'place_gacoan_001',
        review: 'Mie viral sejuta umat. Mie pedas manis dengan taburan ayam cincang melimpah plus dapet pangsit goreng isi ayam yang renyah. Harganya murah kebangetan tapi rasanya emang nagih!',
        rating: 4,
        photoUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800',
        category: 'viral',
    },
    {
        foodName: 'Claypot Siram Daging Sapi',
        locationName: 'Claypot Popo Sabang',
        locationAddress: 'Jl. H. Agus Salim No. 23B, Menteng, Jakarta Pusat',
        latitude: '-6.18652',
        longitude: '106.82489',
        placeId: 'place_popo_001',
        review: 'Hidden gem makanan hangat di daerah Sabang. Nasi claypot dengan siraman kuah telur kental gurih, jagung, dan potongan daging sapi lembut. Sangat comforting dimakan pas lagi hujan!',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
        category: 'hidden_gems',
    },
    {
        foodName: 'Manual Brew Toraja Gayo',
        locationName: 'Kopi Es Tak Kie Glodok',
        locationAddress: 'Gang Gloria, Jl. Pintu Besar Selatan III, Glodok, Jakarta Barat',
        latitude: '-6.14152',
        longitude: '106.81224',
        placeId: 'place_takkie_001',
        review: 'Hidden gem kedai kopi tertua di dalam gang Glodok. Nuansanya jadul banget kayak mesin waktu. Es kopinya tipikal kopi hitam klasik tradisional, strong dan harum luar biasa.',
        rating: 5,
        photoUrl: 'https://images.unsplash.com/photo-1469957905091-15542614b90d?w=800',
        category: 'hidden_gems',
    },
];

export const botComments = [
    'Wah ini sih favorit gue banget! Hampir tiap minggu mampir ke sini.',
    'Ngiler banget liat fotonya, langsung masukin ke kuliner wishlist weekend ini!',
    'Rating 5 emang pantes disandang sih, rasanya ga pernah mengecewakan.',
    'Spill total harganya dong kak, buat porsi segitu worth it banget ga ya?',
    'Setuju banget sama review-nya! Apalagi sambelnya pedes mantap pool bikin nagih.',
    'Wah tersembunyi banget ya tempatnya, tapi emang worth the effort buat dicari.',
    'Udah pernah nyobain sekali pas kebetulan lewat, emang beneran recommended!',
    'Tempatnya asik parah dan pewe banget buat nongkrong sore-sore.',
    'Duh, malem-malem liat postingan kayak gini langsung bikin cacing di perut demo 😭',
    'Baru tau ada tempat makan ini di daerah situ, thanks review jujurnya kak!',
];
